FROM ubuntu:18.04

WORKDIR /usr/src/app

COPY . .

USER 0

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

RUN apt-get install --yes systemd curl git sudo

# Kill all the things we don't need
RUN find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -exec rm \{} \;

RUN mkdir -p /etc/sudoers.d

RUN systemctl set-default multi-user.target

RUN alias python=python3

RUN apt-get install dialog apt-utils -y

RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

RUN ./server/server-setup.sh -y
COPY ./server/settings.yml  ./server/settings.yml
COPY ./client/settings.yml  ./client/settings.yml

EXPOSE 80
EXPOSE 5000

CMD [ "python", "server/server.py" ]